
package pe.edu.ucv.prueba01;
import pe.edu.ucv.prueba01.model.Servicedelview;

public class Catalogo extends javax.swing.JFrame {

private Servicedelview service = new Servicedelview();
    public Catalogo() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jbtnPasteles = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jbtnga2 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jbtnga = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jbtnga3 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jbtnPasteles1 = new javax.swing.JButton();
        jbtnPasteles2 = new javax.swing.JButton();
        jbtnPasteles3 = new javax.swing.JButton();
        jbtnPasteles4 = new javax.swing.JButton();
        jbtnPasteles5 = new javax.swing.JButton();
        jbtnPasteles6 = new javax.swing.JButton();
        jbtnPasteles7 = new javax.swing.JButton();
        jbtnPasteles8 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jbtnPasteles10 = new javax.swing.JButton();
        jbtnPasteles11 = new javax.swing.JButton();
        jbtnPasteles12 = new javax.swing.JButton();
        jbtnPasteles13 = new javax.swing.JButton();
        jbtnPasteles14 = new javax.swing.JButton();
        jbtnPasteles15 = new javax.swing.JButton();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jbtnPasteles16 = new javax.swing.JButton();
        jbtnPasteles17 = new javax.swing.JButton();
        jbtnPasteles18 = new javax.swing.JButton();
        jbtnPasteles19 = new javax.swing.JButton();
        jbtnPasteles20 = new javax.swing.JButton();
        jbtnPasteles21 = new javax.swing.JButton();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jbtnga5 = new javax.swing.JButton();
        jbtnga7 = new javax.swing.JButton();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jbtnga8 = new javax.swing.JButton();
        jTextField30 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnPasteles.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPasteles.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jbtnPasteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pateles.png"))); // NOI18N
        jbtnPasteles.setText("Pasteles");
        jbtnPasteles.setContentAreaFilled(false);
        jbtnPasteles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPasteles.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPasteles.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pateles.png"))); // NOI18N
        jbtnPasteles.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Patelesacolor.png"))); // NOI18N
        jbtnPasteles.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnPasteles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPastelesMouseClicked(evt);
            }
        });
        jbtnPasteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPastelesActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnPasteles, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 190, 270));
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 190, 280));

        jbtnga2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jbtnga2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GalletasSincolor.png"))); // NOI18N
        jbtnga2.setText("Galletas");
        jbtnga2.setContentAreaFilled(false);
        jbtnga2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnga2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnga2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GalletasSincolor.png"))); // NOI18N
        jbtnga2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GalletasConcolor.png"))); // NOI18N
        jbtnga2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnga2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnga2ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnga2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 190, 280));
        jPanel3.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 190, 280));

        jbtnga.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jbtnga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flan Sin Color.jpg"))); // NOI18N
        jbtnga.setText("Flanes");
        jbtnga.setContentAreaFilled(false);
        jbtnga.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnga.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnga.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flan Sin Color.jpg"))); // NOI18N
        jbtnga.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flanes Logo.jpg"))); // NOI18N
        jbtnga.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtngaActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnga, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 190, 280));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 190, 280));

        jbtnga3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jbtnga3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Gelatinanegro.png"))); // NOI18N
        jbtnga3.setText("Gelatinas");
        jbtnga3.setContentAreaFilled(false);
        jbtnga3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnga3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnga3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Gelatinanegro.png"))); // NOI18N
        jbtnga3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen1_1.png"))); // NOI18N
        jbtnga3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnga3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnga3ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnga3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 190, 280));
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 190, 280));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 101, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel8.setBackground(new java.awt.Color(153, 153, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnPasteles1.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPasteles1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbtnPasteles1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pastel de fresa sin color.png"))); // NOI18N
        jbtnPasteles1.setText("Pastel de Fresa");
        jbtnPasteles1.setContentAreaFilled(false);
        jbtnPasteles1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPasteles1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPasteles1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pastel de fresa sin color.png"))); // NOI18N
        jbtnPasteles1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pastel de fresa.jpg"))); // NOI18N
        jbtnPasteles1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnPasteles1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPasteles1MouseClicked(evt);
            }
        });
        jbtnPasteles1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPasteles1ActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnPasteles1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 290, 190, 270));

        jbtnPasteles2.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPasteles2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbtnPasteles2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pie de manzana sin Color.png"))); // NOI18N
        jbtnPasteles2.setText("Pie de Manzana");
        jbtnPasteles2.setContentAreaFilled(false);
        jbtnPasteles2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPasteles2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPasteles2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pie de manzana sin Color.png"))); // NOI18N
        jbtnPasteles2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pay de manzana.jpg"))); // NOI18N
        jbtnPasteles2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnPasteles2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPasteles2MouseClicked(evt);
            }
        });
        jbtnPasteles2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPasteles2ActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnPasteles2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 190, 260));

        jbtnPasteles3.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPasteles3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbtnPasteles3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pastel de Queso Sin Color.png"))); // NOI18N
        jbtnPasteles3.setText("Pastel de Queso");
        jbtnPasteles3.setContentAreaFilled(false);
        jbtnPasteles3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPasteles3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPasteles3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pastel de Queso Sin Color.png"))); // NOI18N
        jbtnPasteles3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pastel de queso.jpg"))); // NOI18N
        jbtnPasteles3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnPasteles3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPasteles3MouseClicked(evt);
            }
        });
        jbtnPasteles3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPasteles3ActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnPasteles3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 190, 270));

        jbtnPasteles4.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPasteles4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbtnPasteles4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pastel de 3 leches sin color.png"))); // NOI18N
        jbtnPasteles4.setText("Pastel de 3 Leches");
        jbtnPasteles4.setContentAreaFilled(false);
        jbtnPasteles4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPasteles4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPasteles4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pastel de 3 leches sin color.png"))); // NOI18N
        jbtnPasteles4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pastel de 3 leches.jpg"))); // NOI18N
        jbtnPasteles4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnPasteles4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPasteles4MouseClicked(evt);
            }
        });
        jbtnPasteles4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPasteles4ActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnPasteles4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 190, 260));

        jbtnPasteles5.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPasteles5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbtnPasteles5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/KEKESin Color.png"))); // NOI18N
        jbtnPasteles5.setText("Keke de Chocolate");
        jbtnPasteles5.setContentAreaFilled(false);
        jbtnPasteles5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPasteles5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPasteles5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/KEKESin Color.png"))); // NOI18N
        jbtnPasteles5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/KEKE.jpg"))); // NOI18N
        jbtnPasteles5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnPasteles5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPasteles5MouseClicked(evt);
            }
        });
        jbtnPasteles5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPasteles5ActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnPasteles5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 190, 260));

        jbtnPasteles6.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPasteles6.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbtnPasteles6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pastel selva negra sin color.png"))); // NOI18N
        jbtnPasteles6.setText("Pastel Selva Negra");
        jbtnPasteles6.setContentAreaFilled(false);
        jbtnPasteles6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPasteles6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPasteles6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pastel selva negra sin color.png"))); // NOI18N
        jbtnPasteles6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pastel Selva Negra (2).jpg"))); // NOI18N
        jbtnPasteles6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnPasteles6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPasteles6MouseClicked(evt);
            }
        });
        jbtnPasteles6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPasteles6ActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnPasteles6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 190, 270));

        jbtnPasteles7.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPasteles7.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbtnPasteles7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moka sin color.png"))); // NOI18N
        jbtnPasteles7.setText("Pastel de Moka");
        jbtnPasteles7.setContentAreaFilled(false);
        jbtnPasteles7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPasteles7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPasteles7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moka sin color.png"))); // NOI18N
        jbtnPasteles7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moka.jpg"))); // NOI18N
        jbtnPasteles7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnPasteles7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPasteles7MouseClicked(evt);
            }
        });
        jbtnPasteles7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPasteles7ActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnPasteles7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 190, 270));

        jbtnPasteles8.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPasteles8.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbtnPasteles8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pie de limon sin color.png"))); // NOI18N
        jbtnPasteles8.setText("Pie de Limon");
        jbtnPasteles8.setContentAreaFilled(false);
        jbtnPasteles8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPasteles8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPasteles8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pie de limon sin color.png"))); // NOI18N
        jbtnPasteles8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pie-de-limon.jpg"))); // NOI18N
        jbtnPasteles8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnPasteles8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPasteles8MouseClicked(evt);
            }
        });
        jbtnPasteles8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPasteles8ActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnPasteles8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 190, 270));
        jPanel8.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 190, 270));
        jPanel8.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 190, 270));
        jPanel8.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 190, 270));
        jPanel8.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 190, 270));
        jPanel8.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 190, 270));
        jPanel8.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 290, 190, 270));
        jPanel8.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 190, 270));
        jPanel8.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 190, 270));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 1151, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel4);

        jPanel11.setBackground(new java.awt.Color(153, 153, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnPasteles10.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPasteles10.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbtnPasteles10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Miloja sin Color.png"))); // NOI18N
        jbtnPasteles10.setText("Miloja");
        jbtnPasteles10.setContentAreaFilled(false);
        jbtnPasteles10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPasteles10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPasteles10.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Miloja sin Color.png"))); // NOI18N
        jbtnPasteles10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Millojas.jpg"))); // NOI18N
        jbtnPasteles10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnPasteles10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPasteles10MouseClicked(evt);
            }
        });
        jbtnPasteles10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPasteles10ActionPerformed(evt);
            }
        });
        jPanel11.add(jbtnPasteles10, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 310, 190, 260));

        jbtnPasteles11.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPasteles11.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbtnPasteles11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Rosquitas Sin color.png"))); // NOI18N
        jbtnPasteles11.setText("Rosquitas");
        jbtnPasteles11.setContentAreaFilled(false);
        jbtnPasteles11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPasteles11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPasteles11.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Rosquitas Sin color.png"))); // NOI18N
        jbtnPasteles11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rosquitas.jpg"))); // NOI18N
        jbtnPasteles11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnPasteles11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPasteles11MouseClicked(evt);
            }
        });
        jbtnPasteles11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPasteles11ActionPerformed(evt);
            }
        });
        jPanel11.add(jbtnPasteles11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 190, 270));

        jbtnPasteles12.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPasteles12.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbtnPasteles12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Alfajor sin color.png"))); // NOI18N
        jbtnPasteles12.setText("Alfajor");
        jbtnPasteles12.setContentAreaFilled(false);
        jbtnPasteles12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPasteles12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPasteles12.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Alfajor sin color.png"))); // NOI18N
        jbtnPasteles12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Alfajores.jpg"))); // NOI18N
        jbtnPasteles12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnPasteles12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPasteles12MouseClicked(evt);
            }
        });
        jbtnPasteles12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPasteles12ActionPerformed(evt);
            }
        });
        jPanel11.add(jbtnPasteles12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 190, 270));

        jbtnPasteles13.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPasteles13.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbtnPasteles13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Empanada Sin color.png"))); // NOI18N
        jbtnPasteles13.setText("Empanada Dulce");
        jbtnPasteles13.setContentAreaFilled(false);
        jbtnPasteles13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPasteles13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPasteles13.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Empanada Sin color.png"))); // NOI18N
        jbtnPasteles13.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Empanadas.jpg"))); // NOI18N
        jbtnPasteles13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnPasteles13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPasteles13MouseClicked(evt);
            }
        });
        jbtnPasteles13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPasteles13ActionPerformed(evt);
            }
        });
        jPanel11.add(jbtnPasteles13, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 190, 270));

        jbtnPasteles14.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPasteles14.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbtnPasteles14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Galleta Rellena sin color.png"))); // NOI18N
        jbtnPasteles14.setText("Empanada Rellena");
        jbtnPasteles14.setContentAreaFilled(false);
        jbtnPasteles14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPasteles14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPasteles14.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Galleta Rellena sin color.png"))); // NOI18N
        jbtnPasteles14.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Galletas rellenas.jpg"))); // NOI18N
        jbtnPasteles14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnPasteles14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPasteles14MouseClicked(evt);
            }
        });
        jbtnPasteles14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPasteles14ActionPerformed(evt);
            }
        });
        jPanel11.add(jbtnPasteles14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 190, 270));

        jbtnPasteles15.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPasteles15.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jbtnPasteles15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Galleta de ChocolateSin color.png"))); // NOI18N
        jbtnPasteles15.setText("Galleta de Chocolate");
        jbtnPasteles15.setContentAreaFilled(false);
        jbtnPasteles15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPasteles15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPasteles15.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Galleta de ChocolateSin color.png"))); // NOI18N
        jbtnPasteles15.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Gelletas de chocolate.jpg"))); // NOI18N
        jbtnPasteles15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnPasteles15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPasteles15MouseClicked(evt);
            }
        });
        jbtnPasteles15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPasteles15ActionPerformed(evt);
            }
        });
        jPanel11.add(jbtnPasteles15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 190, 270));
        jPanel11.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 190, 270));
        jPanel11.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 190, 270));
        jPanel11.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 190, 270));
        jPanel11.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 190, 270));
        jPanel11.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 300, 190, 270));
        jPanel11.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 190, 270));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1151, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab5", jPanel7);

        jPanel9.setBackground(new java.awt.Color(153, 153, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnPasteles16.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPasteles16.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbtnPasteles16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flan de Maracuya Sin color.png"))); // NOI18N
        jbtnPasteles16.setText("Flan de Maracuya");
        jbtnPasteles16.setContentAreaFilled(false);
        jbtnPasteles16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPasteles16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPasteles16.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flan de Maracuya Sin color.png"))); // NOI18N
        jbtnPasteles16.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flan de maracuya.jpg"))); // NOI18N
        jbtnPasteles16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnPasteles16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPasteles16MouseClicked(evt);
            }
        });
        jbtnPasteles16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPasteles16ActionPerformed(evt);
            }
        });
        jPanel9.add(jbtnPasteles16, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 190, 260));

        jbtnPasteles17.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPasteles17.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbtnPasteles17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flan de coco Sin color.png"))); // NOI18N
        jbtnPasteles17.setText("Flan de Coco");
        jbtnPasteles17.setContentAreaFilled(false);
        jbtnPasteles17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPasteles17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPasteles17.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flan de coco Sin color.png"))); // NOI18N
        jbtnPasteles17.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flan-de-coco.jpg"))); // NOI18N
        jbtnPasteles17.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnPasteles17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPasteles17MouseClicked(evt);
            }
        });
        jbtnPasteles17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPasteles17ActionPerformed(evt);
            }
        });
        jPanel9.add(jbtnPasteles17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 190, 270));

        jbtnPasteles18.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPasteles18.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbtnPasteles18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flan de chocolate sin color.png"))); // NOI18N
        jbtnPasteles18.setText("Flan de Chocolate");
        jbtnPasteles18.setContentAreaFilled(false);
        jbtnPasteles18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPasteles18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPasteles18.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flan de chocolate sin color.png"))); // NOI18N
        jbtnPasteles18.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flan de Chocolate.png"))); // NOI18N
        jbtnPasteles18.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnPasteles18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPasteles18MouseClicked(evt);
            }
        });
        jbtnPasteles18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPasteles18ActionPerformed(evt);
            }
        });
        jPanel9.add(jbtnPasteles18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 190, 220));

        jbtnPasteles19.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPasteles19.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbtnPasteles19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flan con gelatina Sin color.png"))); // NOI18N
        jbtnPasteles19.setText("Flan con Gelatina");
        jbtnPasteles19.setContentAreaFilled(false);
        jbtnPasteles19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPasteles19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPasteles19.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flan con gelatina Sin color.png"))); // NOI18N
        jbtnPasteles19.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flan con gelatina.jpg"))); // NOI18N
        jbtnPasteles19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnPasteles19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPasteles19MouseClicked(evt);
            }
        });
        jbtnPasteles19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPasteles19ActionPerformed(evt);
            }
        });
        jPanel9.add(jbtnPasteles19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 190, 270));

        jbtnPasteles20.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPasteles20.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbtnPasteles20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flan napolitano Sin color.png"))); // NOI18N
        jbtnPasteles20.setText("Flan Napolitano");
        jbtnPasteles20.setContentAreaFilled(false);
        jbtnPasteles20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPasteles20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPasteles20.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flan napolitano Sin color.png"))); // NOI18N
        jbtnPasteles20.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flan napolitano color.png"))); // NOI18N
        jbtnPasteles20.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnPasteles20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPasteles20MouseClicked(evt);
            }
        });
        jbtnPasteles20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPasteles20ActionPerformed(evt);
            }
        });
        jPanel9.add(jbtnPasteles20, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 300, 190, 270));

        jbtnPasteles21.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPasteles21.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbtnPasteles21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flan Clasico Sin color.png"))); // NOI18N
        jbtnPasteles21.setText("Flan Clasico");
        jbtnPasteles21.setContentAreaFilled(false);
        jbtnPasteles21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPasteles21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPasteles21.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flan Clasico Sin color.png"))); // NOI18N
        jbtnPasteles21.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flan CLsico.jpg"))); // NOI18N
        jbtnPasteles21.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnPasteles21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPasteles21MouseClicked(evt);
            }
        });
        jbtnPasteles21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPasteles21ActionPerformed(evt);
            }
        });
        jPanel9.add(jbtnPasteles21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 190, 270));
        jPanel9.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 190, 260));
        jPanel9.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 190, 270));
        jPanel9.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 190, 270));
        jPanel9.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 190, 270));
        jPanel9.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 300, 190, 270));
        jPanel9.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 190, 270));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 1151, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", jPanel5);

        jPanel10.setBackground(new java.awt.Color(153, 153, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnga5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbtnga5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Gelatina Blanca Sin color.png"))); // NOI18N
        jbtnga5.setText("Gelatina Mosaiko");
        jbtnga5.setContentAreaFilled(false);
        jbtnga5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnga5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnga5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Gelatina Blanca Sin color.png"))); // NOI18N
        jbtnga5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Gelatina Blanca.jpg"))); // NOI18N
        jbtnga5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnga5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnga5ActionPerformed(evt);
            }
        });
        jPanel10.add(jbtnga5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 190, 270));

        jbtnga7.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbtnga7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Torta elada sin color.png"))); // NOI18N
        jbtnga7.setText("Torta Helada");
        jbtnga7.setContentAreaFilled(false);
        jbtnga7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnga7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnga7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Torta elada sin color.png"))); // NOI18N
        jbtnga7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Torta elada.jpg"))); // NOI18N
        jbtnga7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnga7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnga7ActionPerformed(evt);
            }
        });
        jPanel10.add(jbtnga7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 190, 290));
        jPanel10.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 190, 290));
        jPanel10.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 190, 280));

        jbtnga8.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbtnga8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Gelatina con leche sin color.png"))); // NOI18N
        jbtnga8.setText("Gelatina con Leche");
        jbtnga8.setContentAreaFilled(false);
        jbtnga8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnga8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnga8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Gelatina con leche sin color.png"))); // NOI18N
        jbtnga8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Gelatina con leche.jpg"))); // NOI18N
        jbtnga8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnga8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnga8ActionPerformed(evt);
            }
        });
        jPanel10.add(jbtnga8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 190, 290));
        jPanel10.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 190, 280));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 1151, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", jPanel6);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnga8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnga8ActionPerformed
        service.Catalogoparte2(7);
    }//GEN-LAST:event_jbtnga8ActionPerformed

    private void jbtnga7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnga7ActionPerformed
        service.Catalogoparte2(8);
    }//GEN-LAST:event_jbtnga7ActionPerformed

    private void jbtnga5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnga5ActionPerformed
        service.Catalogoparte2(6);
    }//GEN-LAST:event_jbtnga5ActionPerformed

    private void jbtnPasteles21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPasteles21ActionPerformed
        service.Catalogoparte2(0);
    }//GEN-LAST:event_jbtnPasteles21ActionPerformed

    private void jbtnPasteles21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPasteles21MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPasteles21MouseClicked

    private void jbtnPasteles20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPasteles20ActionPerformed
      service.Catalogoparte2(4);
    }//GEN-LAST:event_jbtnPasteles20ActionPerformed

    private void jbtnPasteles20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPasteles20MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPasteles20MouseClicked

    private void jbtnPasteles19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPasteles19ActionPerformed
        service.Catalogoparte2(3);
    }//GEN-LAST:event_jbtnPasteles19ActionPerformed

    private void jbtnPasteles19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPasteles19MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPasteles19MouseClicked

    private void jbtnPasteles18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPasteles18ActionPerformed
        service.Catalogoparte2(2);
    }//GEN-LAST:event_jbtnPasteles18ActionPerformed

    private void jbtnPasteles18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPasteles18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPasteles18MouseClicked

    private void jbtnPasteles17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPasteles17ActionPerformed
        service.Catalogoparte2(1);
    }//GEN-LAST:event_jbtnPasteles17ActionPerformed

    private void jbtnPasteles17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPasteles17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPasteles17MouseClicked

    private void jbtnPasteles16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPasteles16ActionPerformed
        service.Catalogoparte2(5);
    }//GEN-LAST:event_jbtnPasteles16ActionPerformed

    private void jbtnPasteles16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPasteles16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPasteles16MouseClicked

    private void jbtnPasteles15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPasteles15ActionPerformed
        service.Catalogoparte1(9);
    }//GEN-LAST:event_jbtnPasteles15ActionPerformed

    private void jbtnPasteles15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPasteles15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPasteles15MouseClicked

    private void jbtnPasteles14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPasteles14ActionPerformed
        service.Catalogoparte1(13);
    }//GEN-LAST:event_jbtnPasteles14ActionPerformed

    private void jbtnPasteles14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPasteles14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPasteles14MouseClicked

    private void jbtnPasteles13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPasteles13ActionPerformed
        service.Catalogoparte1(12);
    }//GEN-LAST:event_jbtnPasteles13ActionPerformed

    private void jbtnPasteles13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPasteles13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPasteles13MouseClicked

    private void jbtnPasteles12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPasteles12ActionPerformed
        service.Catalogoparte1(11);
    }//GEN-LAST:event_jbtnPasteles12ActionPerformed

    private void jbtnPasteles12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPasteles12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPasteles12MouseClicked

    private void jbtnPasteles11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPasteles11ActionPerformed
        service.Catalogoparte1(8);
    }//GEN-LAST:event_jbtnPasteles11ActionPerformed

    private void jbtnPasteles11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPasteles11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPasteles11MouseClicked

    private void jbtnPasteles10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPasteles10ActionPerformed
        service.Catalogoparte1(10);
    }//GEN-LAST:event_jbtnPasteles10ActionPerformed

    private void jbtnPasteles10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPasteles10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPasteles10MouseClicked

    private void jbtnPasteles8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPasteles8ActionPerformed
        service.Catalogoparte1(6);
    }//GEN-LAST:event_jbtnPasteles8ActionPerformed

    private void jbtnPasteles8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPasteles8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPasteles8MouseClicked

    private void jbtnPasteles7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPasteles7ActionPerformed
        service.Catalogoparte1(5);
    }//GEN-LAST:event_jbtnPasteles7ActionPerformed

    private void jbtnPasteles7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPasteles7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPasteles7MouseClicked

    private void jbtnPasteles6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPasteles6ActionPerformed
        service.Catalogoparte1(4);
    }//GEN-LAST:event_jbtnPasteles6ActionPerformed

    private void jbtnPasteles6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPasteles6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPasteles6MouseClicked

    private void jbtnPasteles5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPasteles5ActionPerformed
        service.Catalogoparte1(2);
    }//GEN-LAST:event_jbtnPasteles5ActionPerformed

    private void jbtnPasteles5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPasteles5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPasteles5MouseClicked

    private void jbtnPasteles4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPasteles4ActionPerformed
        service.Catalogoparte1(0);
    }//GEN-LAST:event_jbtnPasteles4ActionPerformed

    private void jbtnPasteles4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPasteles4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPasteles4MouseClicked

    private void jbtnPasteles3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPasteles3ActionPerformed
        service.Catalogoparte1(3);
    }//GEN-LAST:event_jbtnPasteles3ActionPerformed

    private void jbtnPasteles3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPasteles3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPasteles3MouseClicked

    private void jbtnPasteles2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPasteles2ActionPerformed
        service.Catalogoparte1(1);
    }//GEN-LAST:event_jbtnPasteles2ActionPerformed

    private void jbtnPasteles2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPasteles2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPasteles2MouseClicked

    private void jbtnPasteles1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPasteles1ActionPerformed
        service.Catalogoparte1(7);
    }//GEN-LAST:event_jbtnPasteles1ActionPerformed

    private void jbtnPasteles1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPasteles1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPasteles1MouseClicked

    private void jbtnga3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnga3ActionPerformed
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_jbtnga3ActionPerformed

    private void jbtngaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtngaActionPerformed
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jbtngaActionPerformed

    private void jbtnga2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnga2ActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jbtnga2ActionPerformed

    private void jbtnPastelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPastelesActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jbtnPastelesActionPerformed

    private void jbtnPastelesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPastelesMouseClicked

    }//GEN-LAST:event_jbtnPastelesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton jbtnPasteles;
    private javax.swing.JButton jbtnPasteles1;
    private javax.swing.JButton jbtnPasteles10;
    private javax.swing.JButton jbtnPasteles11;
    private javax.swing.JButton jbtnPasteles12;
    private javax.swing.JButton jbtnPasteles13;
    private javax.swing.JButton jbtnPasteles14;
    private javax.swing.JButton jbtnPasteles15;
    private javax.swing.JButton jbtnPasteles16;
    private javax.swing.JButton jbtnPasteles17;
    private javax.swing.JButton jbtnPasteles18;
    private javax.swing.JButton jbtnPasteles19;
    private javax.swing.JButton jbtnPasteles2;
    private javax.swing.JButton jbtnPasteles20;
    private javax.swing.JButton jbtnPasteles21;
    private javax.swing.JButton jbtnPasteles3;
    private javax.swing.JButton jbtnPasteles4;
    private javax.swing.JButton jbtnPasteles5;
    private javax.swing.JButton jbtnPasteles6;
    private javax.swing.JButton jbtnPasteles7;
    private javax.swing.JButton jbtnPasteles8;
    private javax.swing.JButton jbtnga;
    private javax.swing.JButton jbtnga2;
    private javax.swing.JButton jbtnga3;
    private javax.swing.JButton jbtnga5;
    private javax.swing.JButton jbtnga7;
    private javax.swing.JButton jbtnga8;
    // End of variables declaration//GEN-END:variables
}
