/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.edu.ucv.prueba01;

/**
 *
 * @author User
 */
public class Contenedordefallas extends javax.swing.JPanel {

    /**
     * Creates new form Contenedordefallas
     */
    public Contenedordefallas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel58 = new javax.swing.JPanel();
        jLabel189 = new javax.swing.JLabel();
        jPanel59 = new javax.swing.JPanel();
        jLabel197 = new javax.swing.JLabel();
        jLabel198 = new javax.swing.JLabel();
        jLabel199 = new javax.swing.JLabel();
        jLabel196 = new javax.swing.JLabel();
        jLabel200 = new javax.swing.JLabel();
        jLabel202 = new javax.swing.JLabel();
        jLabel204 = new javax.swing.JLabel();
        jLabel205 = new javax.swing.JLabel();
        jLabel206 = new javax.swing.JLabel();
        jLabel207 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel60 = new javax.swing.JPanel();
        jLabel190 = new javax.swing.JLabel();
        jLabel201 = new javax.swing.JLabel();
        jPanel61 = new javax.swing.JPanel();
        jLabel203 = new javax.swing.JLabel();
        jLabel208 = new javax.swing.JLabel();
        jLabel209 = new javax.swing.JLabel();
        jLabel210 = new javax.swing.JLabel();
        jLabel212 = new javax.swing.JLabel();
        jLabel213 = new javax.swing.JLabel();
        jLabel214 = new javax.swing.JLabel();
        jLabel215 = new javax.swing.JLabel();
        jLabel216 = new javax.swing.JLabel();
        jLabel217 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel62 = new javax.swing.JPanel();
        jLabel191 = new javax.swing.JLabel();
        jLabel211 = new javax.swing.JLabel();
        jPanel63 = new javax.swing.JPanel();
        jLabel218 = new javax.swing.JLabel();
        jLabel219 = new javax.swing.JLabel();
        jLabel220 = new javax.swing.JLabel();
        jLabel221 = new javax.swing.JLabel();
        jLabel223 = new javax.swing.JLabel();
        jLabel224 = new javax.swing.JLabel();
        jLabel225 = new javax.swing.JLabel();
        jLabel226 = new javax.swing.JLabel();
        jLabel227 = new javax.swing.JLabel();
        jLabel228 = new javax.swing.JLabel();
        jLabel229 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel64 = new javax.swing.JPanel();
        jLabel192 = new javax.swing.JLabel();
        jLabel222 = new javax.swing.JLabel();
        jPanel65 = new javax.swing.JPanel();
        jLabel230 = new javax.swing.JLabel();
        jLabel231 = new javax.swing.JLabel();
        jLabel232 = new javax.swing.JLabel();
        jLabel233 = new javax.swing.JLabel();
        jLabel235 = new javax.swing.JLabel();
        jLabel236 = new javax.swing.JLabel();
        jLabel237 = new javax.swing.JLabel();
        jLabel238 = new javax.swing.JLabel();
        jLabel239 = new javax.swing.JLabel();
        jLabel240 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel66 = new javax.swing.JPanel();
        jLabel193 = new javax.swing.JLabel();
        jLabel234 = new javax.swing.JLabel();
        jPanel67 = new javax.swing.JPanel();
        jLabel241 = new javax.swing.JLabel();
        jLabel242 = new javax.swing.JLabel();
        jLabel243 = new javax.swing.JLabel();
        jLabel244 = new javax.swing.JLabel();
        jLabel246 = new javax.swing.JLabel();
        jLabel247 = new javax.swing.JLabel();
        jLabel248 = new javax.swing.JLabel();
        jLabel249 = new javax.swing.JLabel();
        jLabel250 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel68 = new javax.swing.JPanel();
        jLabel194 = new javax.swing.JLabel();
        jLabel245 = new javax.swing.JLabel();
        jPanel69 = new javax.swing.JPanel();
        jLabel251 = new javax.swing.JLabel();
        jLabel252 = new javax.swing.JLabel();
        jLabel253 = new javax.swing.JLabel();
        jLabel254 = new javax.swing.JLabel();
        jLabel256 = new javax.swing.JLabel();
        jLabel257 = new javax.swing.JLabel();
        jLabel258 = new javax.swing.JLabel();
        jLabel259 = new javax.swing.JLabel();
        jLabel260 = new javax.swing.JLabel();
        jLabel263 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel70 = new javax.swing.JPanel();
        jLabel195 = new javax.swing.JLabel();
        jLabel264 = new javax.swing.JLabel();
        jPanel71 = new javax.swing.JPanel();
        jLabel265 = new javax.swing.JLabel();
        jLabel267 = new javax.swing.JLabel();
        jLabel287 = new javax.swing.JLabel();
        jLabel268 = new javax.swing.JLabel();
        jLabel270 = new javax.swing.JLabel();
        jLabel271 = new javax.swing.JLabel();
        jLabel272 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel72 = new javax.swing.JPanel();
        jLabel269 = new javax.swing.JLabel();
        jPanel73 = new javax.swing.JPanel();
        jLabel273 = new javax.swing.JLabel();
        jLabel275 = new javax.swing.JLabel();
        jLabel292 = new javax.swing.JLabel();
        jLabel276 = new javax.swing.JLabel();
        jLabel277 = new javax.swing.JLabel();
        jLabel279 = new javax.swing.JLabel();
        jLabel280 = new javax.swing.JLabel();
        jLabel281 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel74 = new javax.swing.JPanel();
        jLabel278 = new javax.swing.JLabel();
        jLabel282 = new javax.swing.JLabel();
        jPanel75 = new javax.swing.JPanel();
        jLabel283 = new javax.swing.JLabel();
        jLabel285 = new javax.swing.JLabel();
        jLabel293 = new javax.swing.JLabel();
        jLabel286 = new javax.swing.JLabel();
        jLabel288 = new javax.swing.JLabel();
        jLabel289 = new javax.swing.JLabel();
        jLabel290 = new javax.swing.JLabel();
        jLabel291 = new javax.swing.JLabel();
        jLabel294 = new javax.swing.JLabel();
        jLabel295 = new javax.swing.JLabel();
        jLabel296 = new javax.swing.JLabel();
        jLabel297 = new javax.swing.JLabel();
        jLabel298 = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel58.setBackground(new java.awt.Color(102, 51, 255));

        jLabel189.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel189.setForeground(new java.awt.Color(255, 255, 255));
        jLabel189.setText("Flan Clasico");

        javax.swing.GroupLayout jPanel58Layout = new javax.swing.GroupLayout(jPanel58);
        jPanel58.setLayout(jPanel58Layout);
        jPanel58Layout.setHorizontalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel58Layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jLabel189)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel58Layout.setVerticalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel58Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel189)
                .addContainerGap())
        );

        jPanel4.add(jPanel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 90));

        jPanel59.setBackground(new java.awt.Color(153, 102, 255));
        jPanel59.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel197.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel197.setForeground(new java.awt.Color(255, 255, 255));
        jLabel197.setText("Preparacion");
        jPanel59.add(jLabel197, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel198.setFont(new java.awt.Font("Tahoma", 0, 13));
        jLabel198.setText("<html><LEADING>Para preparar flan, derrite azúcar en una sartén hasta obtener caramelo dorado y viértelo en el fondo de un molde para flan. Bate huevos en un tazón, agrega leche condensada, leche evaporada y extracto de vainilla, mezcla bien. Vierte esta mezcla en el molde con caramelo. Cubre con papel aluminio, coloca el molde en una bandeja de horno con agua caliente hasta la mitad del molde y hornea a 175°C durante 50-60 minutos. Deja enfriar y luego refrigera durante al menos 4 horas. Al servir, pasa un cuchillo alrededor del flan y voltea sobre un plato. ¡Listo para disfrutar de este delicioso postre!");
        jLabel198.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel59.add(jLabel198, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1110, 70));

        jLabel199.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel199.setForeground(new java.awt.Color(255, 255, 255));
        jLabel199.setText("Preparacion:");
        jPanel59.add(jLabel199, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel4.add(jPanel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 1150, 130));

        jLabel196.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/Flan Clasico  .png"))); // NOI18N
        jPanel4.add(jLabel196, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 400, 300));

        jLabel200.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel200.setForeground(new java.awt.Color(255, 255, 255));
        jLabel200.setText("Ingredientes:");
        jPanel4.add(jLabel200, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, -1));

        jLabel202.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel202.setText("1 taza de azúcar");
        jPanel4.add(jLabel202, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 400, 30));

        jLabel204.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel204.setText("4 huevos");
        jPanel4.add(jLabel204, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 400, 30));

        jLabel205.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel205.setText("1 lata (14 oz) de leche condensada ");
        jPanel4.add(jLabel205, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 400, 30));

        jLabel206.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel206.setText("1 lata de leche evaporada ");
        jPanel4.add(jLabel206, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 400, 30));

        jLabel207.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel207.setText("1 cucharadita de extracto de vainilla ");
        jPanel4.add(jLabel207, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 400, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 112, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel3);

        jPanel6.setBackground(new java.awt.Color(102, 102, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel60.setBackground(new java.awt.Color(102, 51, 255));

        jLabel190.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel190.setForeground(new java.awt.Color(255, 255, 255));
        jLabel190.setText("Flan de Coco");

        javax.swing.GroupLayout jPanel60Layout = new javax.swing.GroupLayout(jPanel60);
        jPanel60.setLayout(jPanel60Layout);
        jPanel60Layout.setHorizontalGroup(
            jPanel60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel60Layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jLabel190)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel60Layout.setVerticalGroup(
            jPanel60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel60Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel190)
                .addContainerGap())
        );

        jPanel6.add(jPanel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 90));

        jLabel201.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/Flan de Coco.png"))); // NOI18N
        jPanel6.add(jLabel201, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 300));

        jPanel61.setBackground(new java.awt.Color(153, 102, 255));
        jPanel61.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel203.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel203.setForeground(new java.awt.Color(255, 255, 255));
        jLabel203.setText("Preparacion");
        jPanel61.add(jLabel203, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel208.setFont(new java.awt.Font("Tahoma", 0, 13));
        jLabel208.setText("<html><LEADING>Para hacer flan de coco, derrite azúcar en una sartén hasta obtener un caramelo dorado y viértelo en el fondo de un molde para flan. En un tazón grande, bate huevos y agrega leche condensada, leche de coco y extracto de vainilla, mezcla bien. Vierte esta mezcla en el molde con caramelo y cúbrelo con papel aluminio. Coloca el molde en una bandeja de horno con agua caliente hasta la mitad del molde y hornea a 175°C durante 50-60 minutos, o hasta que un palillo insertado en el centro salga limpio. Deja enfriar a temperatura ambiente y luego refrigera durante al menos 4 horas. Para servir, pasa un cuchillo alrededor del flan, despega del molde y voltea sobre un plato. ¡Listo para disfrutar de este delicioso flan de coco!");
        jLabel208.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel61.add(jLabel208, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1100, 70));

        jLabel209.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel209.setForeground(new java.awt.Color(255, 255, 255));
        jLabel209.setText("Preparacion:");
        jPanel61.add(jLabel209, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel6.add(jPanel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 1150, 160));

        jLabel210.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel210.setForeground(new java.awt.Color(255, 255, 255));
        jLabel210.setText("Ingredientes:");
        jPanel6.add(jLabel210, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, -1, -1));

        jLabel212.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel212.setText("1 taza de azúcar");
        jPanel6.add(jLabel212, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 400, 30));

        jLabel213.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel213.setText("4 huevos");
        jPanel6.add(jLabel213, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 400, 30));

        jLabel214.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel214.setText("1 lata (14 oz) de leche condensada ");
        jPanel6.add(jLabel214, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 400, 30));

        jLabel215.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel215.setText("1 lata de leche de coco (400 ml) ");
        jPanel6.add(jLabel215, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 400, 30));

        jLabel216.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel216.setText("1 cucharadita de extracto de vainilla ");
        jPanel6.add(jLabel216, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 400, 30));

        jLabel217.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel217.setText("20gr ralladura de coco");
        jPanel6.add(jLabel217, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 400, 30));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 99, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel5);

        jPanel8.setBackground(new java.awt.Color(102, 102, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel62.setBackground(new java.awt.Color(102, 51, 255));

        jLabel191.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel191.setForeground(new java.awt.Color(255, 255, 255));
        jLabel191.setText("Flan de Chocolate");

        javax.swing.GroupLayout jPanel62Layout = new javax.swing.GroupLayout(jPanel62);
        jPanel62.setLayout(jPanel62Layout);
        jPanel62Layout.setHorizontalGroup(
            jPanel62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel62Layout.createSequentialGroup()
                .addContainerGap(373, Short.MAX_VALUE)
                .addComponent(jLabel191)
                .addGap(348, 348, 348))
        );
        jPanel62Layout.setVerticalGroup(
            jPanel62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel62Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel191)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 90));

        jLabel211.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/Flan de chocolate.png"))); // NOI18N
        jPanel8.add(jLabel211, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 390, 290));

        jPanel63.setBackground(new java.awt.Color(153, 102, 255));
        jPanel63.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel218.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel218.setForeground(new java.awt.Color(255, 255, 255));
        jLabel218.setText("Preparacion");
        jPanel63.add(jLabel218, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel219.setFont(new java.awt.Font("Tahoma", 0, 13));
        jLabel219.setText("<html><LEADING>Para preparar un delicioso flan de chocolate, carameliza azúcar hasta obtener caramelo y viértelo en un molde para flan. Luego, en un tazón grande, combina huevos, leche condensada, leche entera, cacao en polvo, extracto de vainilla y una pizca de sal, asegurándote de mezclar bien. Vierte esta mezcla en el molde caramelizado y cúbrelo con papel aluminio. Hornea a 175°C en un baño de agua durante 60-70 minutos, o hasta que un palillo en el centro salga limpio. Tras enfriar a temperatura ambiente y refrigerar durante al menos 4 horas, desmolda el flan al pasar un cuchillo alrededor, luego voltea sobre un plato y disfruta de este irresistible flan de chocolate.");
        jLabel219.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel63.add(jLabel219, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1120, 70));

        jLabel220.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel220.setForeground(new java.awt.Color(255, 255, 255));
        jLabel220.setText("Preparacion:");
        jPanel63.add(jLabel220, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel8.add(jPanel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 1150, 160));

        jLabel221.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel221.setForeground(new java.awt.Color(255, 255, 255));
        jLabel221.setText("Ingredientes:");
        jPanel8.add(jLabel221, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, -1, -1));

        jLabel223.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel223.setText("1 taza de azúcar");
        jPanel8.add(jLabel223, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 400, 30));

        jLabel224.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel224.setText("4 huevos");
        jPanel8.add(jLabel224, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 400, 30));

        jLabel225.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel225.setText("1 lata (14 oz) de leche condensada ");
        jPanel8.add(jLabel225, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 400, 30));

        jLabel226.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel226.setText("2 tazas de leche entera ");
        jPanel8.add(jLabel226, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 400, 30));

        jLabel227.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel227.setText("1/2 taza de cacao en polvo ");
        jPanel8.add(jLabel227, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 400, 30));

        jLabel228.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel228.setText("1 cucharadita de extracto de vainilla ");
        jPanel8.add(jLabel228, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 400, 30));

        jLabel229.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel229.setText("Una pizca de sal ");
        jPanel8.add(jLabel229, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 400, 30));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel7);

        jPanel10.setBackground(new java.awt.Color(102, 102, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel64.setBackground(new java.awt.Color(102, 51, 255));

        jLabel192.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel192.setForeground(new java.awt.Color(255, 255, 255));
        jLabel192.setText("Flan con Gelatina");

        javax.swing.GroupLayout jPanel64Layout = new javax.swing.GroupLayout(jPanel64);
        jPanel64.setLayout(jPanel64Layout);
        jPanel64Layout.setHorizontalGroup(
            jPanel64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel64Layout.createSequentialGroup()
                .addContainerGap(376, Short.MAX_VALUE)
                .addComponent(jLabel192)
                .addGap(356, 356, 356))
        );
        jPanel64Layout.setVerticalGroup(
            jPanel64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel64Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel192)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 90));

        jLabel222.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/FLan con gelatina .png"))); // NOI18N
        jPanel10.add(jLabel222, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 400, 300));

        jPanel65.setBackground(new java.awt.Color(153, 102, 255));
        jPanel65.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel230.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel230.setForeground(new java.awt.Color(255, 255, 255));
        jLabel230.setText("Preparacion");
        jPanel65.add(jLabel230, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel231.setFont(new java.awt.Font("Tahoma", 0, 13));
        jLabel231.setText("<html><LEADING>Preparar un flan con gelatina es sencillo: primero, carameliza una taza de azúcar y vierte el caramelo en un molde. Luego, en un tazón, bate 4 huevos, agrega una lata de leche condensada, dos latas de leche entera y extracto de vainilla; vierte esta mezcla en el molde caramelizado. Hornea a 175°C en baño de agua por 60-70 minutos. Tras enfriar y refrigerar durante 4 horas, prepara gelatina siguiendo las instrucciones, enfríala sin que solidifique por completo y viértela sobre el flan. Refrigera nuevamente hasta que la gelatina esté firme. Al desmoldar con cuidado, disfruta de un delicioso flan con un toque de gelatina.");
        jLabel231.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel65.add(jLabel231, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1100, 70));

        jLabel232.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel232.setForeground(new java.awt.Color(255, 255, 255));
        jLabel232.setText("Preparacion:");
        jPanel65.add(jLabel232, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel10.add(jPanel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 1150, 160));

        jLabel233.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel233.setForeground(new java.awt.Color(255, 255, 255));
        jLabel233.setText("Ingredientes:");
        jPanel10.add(jLabel233, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, -1));

        jLabel235.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel235.setText("1 taza de azúcar");
        jPanel10.add(jLabel235, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 400, 30));

        jLabel236.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel236.setText("4 huevos ");
        jPanel10.add(jLabel236, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 400, 30));

        jLabel237.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel237.setText("1 lata (14 oz) de leche condensada ");
        jPanel10.add(jLabel237, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 400, 30));

        jLabel238.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel238.setText("2 latas de leche entera");
        jPanel10.add(jLabel238, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 400, 30));

        jLabel239.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel239.setText("1 cucharadita de extracto de vainilla ");
        jPanel10.add(jLabel239, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 400, 30));

        jLabel240.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel240.setText("1 paquete (85 g) de gelatina");
        jPanel10.add(jLabel240, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 400, 30));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 82, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", jPanel9);

        jPanel12.setBackground(new java.awt.Color(102, 102, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel66.setBackground(new java.awt.Color(102, 51, 255));

        jLabel193.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel193.setForeground(new java.awt.Color(255, 255, 255));
        jLabel193.setText("Flan Napolitano");

        javax.swing.GroupLayout jPanel66Layout = new javax.swing.GroupLayout(jPanel66);
        jPanel66.setLayout(jPanel66Layout);
        jPanel66Layout.setHorizontalGroup(
            jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel66Layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jLabel193)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel66Layout.setVerticalGroup(
            jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel66Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel193)
                .addContainerGap())
        );

        jPanel12.add(jPanel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 90));

        jLabel234.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/Flan Napolitano.png"))); // NOI18N
        jPanel12.add(jLabel234, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 390, 290));

        jPanel67.setBackground(new java.awt.Color(153, 102, 255));
        jPanel67.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel241.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel241.setForeground(new java.awt.Color(255, 255, 255));
        jLabel241.setText("Preparacion");
        jPanel67.add(jLabel241, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel242.setFont(new java.awt.Font("Tahoma", 0, 13));
        jLabel242.setText("<html><LEADING>Para preparar flan, derrite 1 taza de azúcar en una sartén hasta obtener un caramelo dorado y viértelo en el fondo de un molde para flan. Bate 4 huevos y agrega 1 lata de leche condensada, 2 latas de leche entera y 1 cucharadita de extracto de vainilla. Vierte esta mezcla sobre el caramelo en el molde. Cubre con papel aluminio, coloca el molde en una bandeja con agua caliente y hornea a 175°C durante 60-70 minutos. Deja enfriar y refrigera. Para servir, pasa un cuchillo alrededor del flan y desmolda. ¡Listo para disfrutar de este delicioso postre!");
        jLabel242.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel67.add(jLabel242, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1110, 70));

        jLabel243.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel243.setForeground(new java.awt.Color(255, 255, 255));
        jLabel243.setText("Preparacion:");
        jPanel67.add(jLabel243, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel12.add(jPanel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 1150, 150));

        jLabel244.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel244.setForeground(new java.awt.Color(255, 255, 255));
        jLabel244.setText("Ingredientes:");
        jPanel12.add(jLabel244, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, -1));

        jLabel246.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel246.setText("1 taza de azúcar");
        jPanel12.add(jLabel246, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 400, 30));

        jLabel247.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel247.setText("4 huevos");
        jPanel12.add(jLabel247, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 400, 30));

        jLabel248.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel248.setText("1 lata (14 oz) de leche condensada ");
        jPanel12.add(jLabel248, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 400, 30));

        jLabel249.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel249.setText("2 latas de leche entera");
        jPanel12.add(jLabel249, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 400, 30));

        jLabel250.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel250.setText("1 cucharadita de extracto de vainilla ");
        jPanel12.add(jLabel250, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 400, 30));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 99, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab5", jPanel11);

        jPanel14.setBackground(new java.awt.Color(102, 102, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel68.setBackground(new java.awt.Color(102, 51, 255));

        jLabel194.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel194.setForeground(new java.awt.Color(255, 255, 255));
        jLabel194.setText("Flan de Maracuya");

        javax.swing.GroupLayout jPanel68Layout = new javax.swing.GroupLayout(jPanel68);
        jPanel68.setLayout(jPanel68Layout);
        jPanel68Layout.setHorizontalGroup(
            jPanel68Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel68Layout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addComponent(jLabel194)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel68Layout.setVerticalGroup(
            jPanel68Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel68Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel194)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14.add(jPanel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 90));

        jLabel245.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/Flan de Maracuya.png"))); // NOI18N
        jPanel14.add(jLabel245, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 400, 300));

        jPanel69.setBackground(new java.awt.Color(153, 102, 255));
        jPanel69.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel251.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel251.setForeground(new java.awt.Color(255, 255, 255));
        jLabel251.setText("Preparacion");
        jPanel69.add(jLabel251, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel252.setFont(new java.awt.Font("Tahoma", 0, 13));
        jLabel252.setText("<html><LEADING>Comienza precalentando el horno a 180°C. En una sartén, derrite una taza de azúcar para hacer un caramelo dorado y viértelo en el fondo de un molde para flan, dejando que se enfríe. En un tazón grande, mezcla huevos, leche condensada, leche evaporada y pulpa de maracuyá hasta obtener una mezcla uniforme. Vierte esta mezcla sobre el caramelo en el molde, cúbrelo con papel aluminio y hornea en una bandeja con agua caliente durante aproximadamente 1 hora. Después de enfriar a temperatura ambiente, refrigera el flan durante al menos 3 horas o toda la noche. Al servir, desmolda el flan volteándolo sobre un plato, permitiendo que el caramelo quede en la parte superior. ¡Listo para disfrutar de un postre delicioso y refrescante!");
        jLabel252.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel69.add(jLabel252, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1120, 70));

        jLabel253.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel253.setForeground(new java.awt.Color(255, 255, 255));
        jLabel253.setText("Preparacion:");
        jPanel69.add(jLabel253, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel14.add(jPanel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 1160, 140));

        jLabel254.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel254.setForeground(new java.awt.Color(255, 255, 255));
        jLabel254.setText("Ingredientes:");
        jPanel14.add(jLabel254, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        jLabel256.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel256.setText("4 huevos");
        jPanel14.add(jLabel256, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 400, 30));

        jLabel257.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel257.setText("1 lata de leche condensada ");
        jPanel14.add(jLabel257, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 400, 30));

        jLabel258.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel258.setText("1 lata de leche evaporada");
        jPanel14.add(jLabel258, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 400, 30));

        jLabel259.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel259.setText("Pulpa de maracuyá de 4 maracuyás ");
        jPanel14.add(jLabel259, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 400, 30));

        jLabel260.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel260.setText("1 cucharadita de esencia de vainilla ");
        jPanel14.add(jLabel260, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 400, 30));

        jLabel263.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel263.setText("1 taza de azúcar ");
        jPanel14.add(jLabel263, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 400, 40));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 102, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab6", jPanel13);

        jPanel16.setBackground(new java.awt.Color(102, 102, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel70.setBackground(new java.awt.Color(102, 51, 255));

        jLabel195.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel195.setForeground(new java.awt.Color(255, 255, 255));
        jLabel195.setText("Gelatina de Mosaico");

        javax.swing.GroupLayout jPanel70Layout = new javax.swing.GroupLayout(jPanel70);
        jPanel70.setLayout(jPanel70Layout);
        jPanel70Layout.setHorizontalGroup(
            jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel70Layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(jLabel195)
                .addContainerGap(361, Short.MAX_VALUE))
        );
        jPanel70Layout.setVerticalGroup(
            jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel70Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel195)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel16.add(jPanel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 90));

        jLabel264.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/gelatina mosaiko.png"))); // NOI18N
        jPanel16.add(jLabel264, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 400, 280));

        jPanel71.setBackground(new java.awt.Color(153, 102, 255));
        jPanel71.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel265.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel265.setForeground(new java.awt.Color(255, 255, 255));
        jLabel265.setText("Preparacion");
        jPanel71.add(jLabel265, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel267.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel267.setForeground(new java.awt.Color(255, 255, 255));
        jLabel267.setText("Preparacion:");
        jPanel71.add(jLabel267, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel287.setFont(new java.awt.Font("Tahoma", 0, 13));
        jLabel287.setText("<html><LEADING>Prepara dos paquetes de gelatina de sabores diferentes según las indicaciones del paquete. Agrega 1 lata de leche condensada a cada gelatina y mezcla. Deja enfriar pero no solidifica por completo. Vierte una capa de una gelatina sobre el flan napolitano ya enfriado y refrigera. Luego, vierte una capa de la otra gelatina sobre la primera capa ya solidificada y refrigera nuevamente");
        jLabel287.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel71.add(jLabel287, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1100, 70));

        jPanel16.add(jPanel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 1150, 150));

        jLabel268.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel268.setForeground(new java.awt.Color(255, 255, 255));
        jLabel268.setText("Ingredientes:");
        jPanel16.add(jLabel268, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

        jLabel270.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel270.setText("3 paquetes de gelatina de sabor a elección");
        jPanel16.add(jLabel270, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 400, 30));

        jLabel271.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel271.setText("Agua caliente");
        jPanel16.add(jLabel271, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 400, 30));

        jLabel272.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel272.setText("1 lata de leche condensada por cada paquete de gelatina ");
        jPanel16.add(jLabel272, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 460, 30));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 92, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab7", jPanel15);

        jPanel18.setBackground(new java.awt.Color(102, 102, 255));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel72.setBackground(new java.awt.Color(102, 51, 255));

        jLabel269.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel269.setForeground(new java.awt.Color(255, 255, 255));
        jLabel269.setText("Gelatina con Leche");

        javax.swing.GroupLayout jPanel72Layout = new javax.swing.GroupLayout(jPanel72);
        jPanel72.setLayout(jPanel72Layout);
        jPanel72Layout.setHorizontalGroup(
            jPanel72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel72Layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jLabel269)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel72Layout.setVerticalGroup(
            jPanel72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel72Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel269)
                .addContainerGap())
        );

        jPanel18.add(jPanel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 90));

        jPanel73.setBackground(new java.awt.Color(153, 102, 255));
        jPanel73.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel273.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel273.setForeground(new java.awt.Color(255, 255, 255));
        jLabel273.setText("Preparacion");
        jPanel73.add(jLabel273, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel275.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel275.setForeground(new java.awt.Color(255, 255, 255));
        jLabel275.setText("Preparacion:");
        jPanel73.add(jLabel275, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel292.setFont(new java.awt.Font("Tahoma", 0, 13));
        jLabel292.setText("<html><LEADING>Primero hidratamos la gelatina en agua fría y luego la incorporamos a la leche caliente, endulzada a nuestro gusto. Después de mezclar bien y asegurarnos de que la gelatina se disuelva por completo, dejamos enfriar la mezcla antes de refrigerarla para que adquiera firmeza. Este refrescante postre es versátil y se puede personalizar con sabores adicionales, como vainilla o frutas. Una vez que la gelatina ha cuajado, está lista para ser disfrutada en cualquier momento, ya sea cortada en porciones individuales o servida directamente del recipiente");
        jLabel292.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel73.add(jLabel292, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1110, 60));

        jPanel18.add(jPanel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 1150, 150));

        jLabel276.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/Gelatina con leche.png"))); // NOI18N
        jPanel18.add(jLabel276, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 400, 300));

        jLabel277.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel277.setForeground(new java.awt.Color(255, 255, 255));
        jLabel277.setText("Ingredientes:");
        jPanel18.add(jLabel277, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, -1, -1));

        jLabel279.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel279.setText("1 paquete de gelatina");
        jPanel18.add(jLabel279, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 400, 30));

        jLabel280.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel280.setText("Agua caliente ");
        jPanel18.add(jLabel280, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 400, 30));

        jLabel281.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel281.setText("1 lata de leche evaporada ");
        jPanel18.add(jLabel281, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 400, 30));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 92, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab8", jPanel17);

        jPanel20.setBackground(new java.awt.Color(102, 102, 255));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel74.setBackground(new java.awt.Color(102, 51, 255));

        jLabel278.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel278.setForeground(new java.awt.Color(255, 255, 255));
        jLabel278.setText("Torta Helada");

        javax.swing.GroupLayout jPanel74Layout = new javax.swing.GroupLayout(jPanel74);
        jPanel74.setLayout(jPanel74Layout);
        jPanel74Layout.setHorizontalGroup(
            jPanel74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel74Layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(jLabel278)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel74Layout.setVerticalGroup(
            jPanel74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel74Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel278)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel20.add(jPanel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 90));

        jLabel282.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2/Torta Helada.png"))); // NOI18N
        jPanel20.add(jLabel282, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 400, 290));

        jPanel75.setBackground(new java.awt.Color(153, 102, 255));
        jPanel75.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel283.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel283.setForeground(new java.awt.Color(255, 255, 255));
        jLabel283.setText("Preparacion");
        jPanel75.add(jLabel283, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel285.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel285.setForeground(new java.awt.Color(255, 255, 255));
        jLabel285.setText("Preparacion:");
        jPanel75.add(jLabel285, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel293.setFont(new java.awt.Font("Tahoma", 0, 13));
        jLabel293.setText("<html><LEADING>Para preparar esta exquisita torta, comienza batiendo los huevos hasta que espumen, luego agrega el azúcar y la vainilla gradualmente, batiendo hasta que la mezcla triplique su volumen. Incorpora cuidadosamente harina y sal cernidas con movimientos envolventes. Vierte la mezcla en un molde preparado y hornea hasta que al insertar un palillo, este salga limpio. Después de enfriar y cortar en discos, engrasa otro molde y vierte gelatina disuelta con duraznos, refrigerando hasta cuajar. Hidrata y derrite colapez, incorporándola a una mezcla batida de leche congelada para formar la carlota de fresa. Assemble las capas: gelatina, disco de bizcocho, y carlota, repitiendo el proceso. Refrigera la torta toda la noche y, al desmoldar, sumérjela brevemente en agua caliente para obtener una presentación perfecta. ¡Disfruta de esta deliciosa torta helada de durazno y fresa!");
        jLabel293.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel75.add(jLabel293, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1120, 80));

        jPanel20.add(jPanel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 1150, 160));

        jLabel286.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel286.setForeground(new java.awt.Color(255, 255, 255));
        jLabel286.setText("Ingredientes:");
        jPanel20.add(jLabel286, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        jLabel288.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel288.setText("180 gramos de harina sin preparar");
        jPanel20.add(jLabel288, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 400, 30));

        jLabel289.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel289.setText("6 huevos");
        jPanel20.add(jLabel289, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 400, 30));

        jLabel290.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel290.setText("180 gramos de azúcar");
        jPanel20.add(jLabel290, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 400, 30));

        jLabel291.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel291.setText("1 cucharadita de esencia de vainilla");
        jPanel20.add(jLabel291, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 400, 30));

        jLabel294.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel294.setText("320 gramos de gelatina de fresa");
        jPanel20.add(jLabel294, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 400, 30));

        jLabel295.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel295.setText("2 tasas de agua y 2 de agua caliente");
        jPanel20.add(jLabel295, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 400, 30));

        jLabel296.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel296.setText("25 gramos de colapez en polvo");
        jPanel20.add(jLabel296, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 400, 30));

        jLabel297.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel297.setText("1 tableta de chocolate");
        jPanel20.add(jLabel297, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 400, 30));

        jLabel298.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel298.setText("1 ½ latas de leche evaporada congelada");
        jPanel20.add(jLabel298, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 400, 30));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 92, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab9", jPanel19);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel189;
    private javax.swing.JLabel jLabel190;
    private javax.swing.JLabel jLabel191;
    private javax.swing.JLabel jLabel192;
    private javax.swing.JLabel jLabel193;
    private javax.swing.JLabel jLabel194;
    private javax.swing.JLabel jLabel195;
    private javax.swing.JLabel jLabel196;
    private javax.swing.JLabel jLabel197;
    private javax.swing.JLabel jLabel198;
    private javax.swing.JLabel jLabel199;
    private javax.swing.JLabel jLabel200;
    private javax.swing.JLabel jLabel201;
    private javax.swing.JLabel jLabel202;
    private javax.swing.JLabel jLabel203;
    private javax.swing.JLabel jLabel204;
    private javax.swing.JLabel jLabel205;
    private javax.swing.JLabel jLabel206;
    private javax.swing.JLabel jLabel207;
    private javax.swing.JLabel jLabel208;
    private javax.swing.JLabel jLabel209;
    private javax.swing.JLabel jLabel210;
    private javax.swing.JLabel jLabel211;
    private javax.swing.JLabel jLabel212;
    private javax.swing.JLabel jLabel213;
    private javax.swing.JLabel jLabel214;
    private javax.swing.JLabel jLabel215;
    private javax.swing.JLabel jLabel216;
    private javax.swing.JLabel jLabel217;
    private javax.swing.JLabel jLabel218;
    private javax.swing.JLabel jLabel219;
    private javax.swing.JLabel jLabel220;
    private javax.swing.JLabel jLabel221;
    private javax.swing.JLabel jLabel222;
    private javax.swing.JLabel jLabel223;
    private javax.swing.JLabel jLabel224;
    private javax.swing.JLabel jLabel225;
    private javax.swing.JLabel jLabel226;
    private javax.swing.JLabel jLabel227;
    private javax.swing.JLabel jLabel228;
    private javax.swing.JLabel jLabel229;
    private javax.swing.JLabel jLabel230;
    private javax.swing.JLabel jLabel231;
    private javax.swing.JLabel jLabel232;
    private javax.swing.JLabel jLabel233;
    private javax.swing.JLabel jLabel234;
    private javax.swing.JLabel jLabel235;
    private javax.swing.JLabel jLabel236;
    private javax.swing.JLabel jLabel237;
    private javax.swing.JLabel jLabel238;
    private javax.swing.JLabel jLabel239;
    private javax.swing.JLabel jLabel240;
    private javax.swing.JLabel jLabel241;
    private javax.swing.JLabel jLabel242;
    private javax.swing.JLabel jLabel243;
    private javax.swing.JLabel jLabel244;
    private javax.swing.JLabel jLabel245;
    private javax.swing.JLabel jLabel246;
    private javax.swing.JLabel jLabel247;
    private javax.swing.JLabel jLabel248;
    private javax.swing.JLabel jLabel249;
    private javax.swing.JLabel jLabel250;
    private javax.swing.JLabel jLabel251;
    private javax.swing.JLabel jLabel252;
    private javax.swing.JLabel jLabel253;
    private javax.swing.JLabel jLabel254;
    private javax.swing.JLabel jLabel256;
    private javax.swing.JLabel jLabel257;
    private javax.swing.JLabel jLabel258;
    private javax.swing.JLabel jLabel259;
    private javax.swing.JLabel jLabel260;
    private javax.swing.JLabel jLabel263;
    private javax.swing.JLabel jLabel264;
    private javax.swing.JLabel jLabel265;
    private javax.swing.JLabel jLabel267;
    private javax.swing.JLabel jLabel268;
    private javax.swing.JLabel jLabel269;
    private javax.swing.JLabel jLabel270;
    private javax.swing.JLabel jLabel271;
    private javax.swing.JLabel jLabel272;
    private javax.swing.JLabel jLabel273;
    private javax.swing.JLabel jLabel275;
    private javax.swing.JLabel jLabel276;
    private javax.swing.JLabel jLabel277;
    private javax.swing.JLabel jLabel278;
    private javax.swing.JLabel jLabel279;
    private javax.swing.JLabel jLabel280;
    private javax.swing.JLabel jLabel281;
    private javax.swing.JLabel jLabel282;
    private javax.swing.JLabel jLabel283;
    private javax.swing.JLabel jLabel285;
    private javax.swing.JLabel jLabel286;
    private javax.swing.JLabel jLabel287;
    private javax.swing.JLabel jLabel288;
    private javax.swing.JLabel jLabel289;
    private javax.swing.JLabel jLabel290;
    private javax.swing.JLabel jLabel291;
    private javax.swing.JLabel jLabel292;
    private javax.swing.JLabel jLabel293;
    private javax.swing.JLabel jLabel294;
    private javax.swing.JLabel jLabel295;
    private javax.swing.JLabel jLabel296;
    private javax.swing.JLabel jLabel297;
    private javax.swing.JLabel jLabel298;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel67;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel69;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel70;
    private javax.swing.JPanel jPanel71;
    private javax.swing.JPanel jPanel72;
    private javax.swing.JPanel jPanel73;
    private javax.swing.JPanel jPanel74;
    private javax.swing.JPanel jPanel75;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
